// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    01_command: typeof import('./src/components/01_command.vue')['default']
    02_Ref: typeof import('./src/components/02_Ref.vue')['default']
    03_Reactive: typeof import('./src/components/03_Reactive.vue')['default']
    04_to: typeof import('./src/components/04_to.vue')['default']
    05_computed: typeof import('./src/components/05_computed.vue')['default']
    06_watch: typeof import('./src/components/06_watch.vue')['default']
    07_live: typeof import('./src/components/07_live.vue')['default']
    A: typeof import('./src/components/A.vue')['default']
    B: typeof import('./src/components/B.vue')['default']
    C: typeof import('./src/components/C.vue')['default']
    Card: typeof import('./src/components/card/index.vue')['default']
    Dialog: typeof import('./src/components/Dialog/index.vue')['default']
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElCheckbox: typeof import('element-plus/es/el-checkbox')['default']
    ElCheckboxGroup: typeof import('element-plus/es/el-checkbox-group')['default']
    ElCol: typeof import('element-plus/es/el-col')['default']
    ElDatePicker: typeof import('element-plus/es/el-date-picker')['default']
    ElForm: typeof import('element-plus/es/el-form')['default']
    ElFormItem: typeof import('element-plus/es/el-form-item')['default']
    ElIcon: typeof import('element-plus/es/el-icon')['default']
    ElInput: typeof import('element-plus/es/el-input')['default']
    ElOption: typeof import('element-plus/es/el-option')['default']
    ElRadio: typeof import('element-plus/es/el-radio')['default']
    ElRadioGroup: typeof import('element-plus/es/el-radio-group')['default']
    ElSelect: typeof import('element-plus/es/el-select')['default']
    ElSwitch: typeof import('element-plus/es/el-switch')['default']
    ElTimePicker: typeof import('element-plus/es/el-time-picker')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    KeepAlive: typeof import('./src/components/keep-alive.vue')['default']
    KeepAlive2: typeof import('./src/components/keep-alive2.vue')['default']
    Tree: typeof import('./src/components/Tree/index.vue')['default']
  }
}
